#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# Patch live php-fpm pool.d config files and Hestia's templates
/usr/local/hestia/bin/v-invoke-plugin wp_global_patch_all

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "WP Global" "<span style=\"color:#4DA6FF;\"><i class=\"fas fa-wordpress\"></i></span> WP Global plugin has finished installing."
