#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

php -r <<'EOF'
require_once( '/usr/local/hestia/web/pluginable.php' );
global $hcpp;

$hcpp->do_action( 'wp_global_pre_patch' );

// Patch Hestia templates php-fpm templates ..templates/web/php-fpm/*.tpl
$folderPath = "/usr/local/hestia/data/templates/web/php-fpm";
$files = glob( "$folderPath/*.tpl" );
foreach( $files as $file ) {
    if ( strpos( $file, 'no-php.tpl' ) !== false ) {
        continue;
    }
    // Patch php-fpm templates open_basedir to include /home/%user%/web/wp-global
    $hcpp->patch_file( 
        $file,
        ":/usr/local/hestia/plugins:",
        ":/usr/local/hestia/plugins:/home/%user%/web/wp-global:"
    );
}
EOF

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "WP Global" "<span style=\"color:#4DA6FF;\"><i class=\"fas fa-wordpress\"></i></span> WP Global plugin has finished installing."
